name: test and build
on:
  workflow_call:
    outputs:
      image_tag:
        description: "test"
        value: ${{ jobs.test.outputs.image_tags }}

jobs: 
  test:
    runs-on: ubuntu-18.04
    outputs:
      image_tags: "my_tag"
    steps: 
    - name: Step1A
      run: |
        echo "Step1A"

    - name: debug output on test job
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "github ref: ${{ github.ref }}" 
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "event name: ${{ github.event_name }}"
        echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Step 1B # force a failure
      run: |
        echo "build step"
        exit 1 